> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Diving into Numpy


### Exploring interesting numpy functions

Write a short introduction about Numpy and list the chosen functions. 

1. np.nditer()
2. np.sort()
3. np.count_nonzero()
4. np.array_split()
5. np.where()

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Creating a new project "msoni00005/numpy-array-operations"
[jovian] Committed successfully! https://jovian.ai/msoni00005/numpy-array-operations


'https://jovian.ai/msoni00005/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [43]:
# List of functions explained 
function1 = np.nditer  
function2 = np.sort
function3 = np.count_nonzero
function4 = np.array_split
function5 = np.where

## Function 1 - np.nditer()

This function is very helpful when we need to iterate over elements (scalars) of a numpy array.It eliminates the need of writing 'n' for loops for iterating over 'n' dimension array.

ARGUMENTS :
as an argument to the function we pass the numpy array whose elements we want to print or iterate over

SYNTAX:
np.nditer(arr) : arr is an array

In [14]:
# Example 1 - working (change this)
arr1 = np.array([[1, 2], 
        [3, 4.],
        [5,6],
        [7,8]])

 

for x in (np.nditer(arr1)):
    print(x)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0


The np.nditer has iterated over elements of array in scalar fashion using only 1 for loops unlike 2 for loops which would have been required to iterate over 2D array.

In [11]:
# Example 2 - working
arr1

for x in np.nditer(arr1[:,::2]) :
    print(x)

1.0
3.0
5.0
7.0


Here in this example , I have demonstrated that how we can also apply filtering to skip some elements
Here we are skipping 1 element in axis 1 which is written as arr1[:,::2]

In [13]:
# Example 3 - breaking (to illustrate when it breaks)
arr1

for x in np.nditer(arr1[4]):
    print(x)

IndexError: index 4 is out of bounds for axis 0 with size 4

This code fails because of IndexOutOfBounds error. We asked it iterate from 4th index in the outermost dimension or axis 0 but it had only 4 elements(upto index 3) which made the code to break.

It can be fixed by giving correct dimension as an array index.

This function can prove to be of great help when we want to iterate over array elements in a high dimensionality array , where writing that many for loops can be a cumbersome task

In [14]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "msoni00005/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/msoni00005/numpy-array-operations


'https://jovian.ai/msoni00005/numpy-array-operations'

## Function 2 - np.sort()

This function sorts the elements of an array.If the array elements are strings then they are sorted alphabetically.This method returns a copy of array leaving original array unchanged.

ARGUMENTS:
np.sort(arr,axis='value') : this function takes an array and an optional parameter axis as an argument.If we dont mention axis then elements get sorted along each axis.

In [15]:
# Example 1 - working
arr2 = np.array([9,7,8,6,5,4,1,3,2]).reshape(3,3)
arr2

np.sort(arr2)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

Here the arr2 elements has been sorted in ascending order.Since we skipped optional axis parameter ,elements have been sorted along each axis

In [16]:
# Example 2 - working
arr3 = np.array(['apples','cherry','mangoes','banana','dates','plums'])
arr3

np.sort(arr3)

array(['apples', 'banana', 'cherry', 'dates', 'mangoes', 'plums'],
      dtype='<U7')

Array3 being an array of strings, so it has been sorted according to alphabetic order.

In [22]:
# Example 3 - breaking (to illustrate when it breaks)
arr2
np.sort(arr2,axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

arr2 is a 2D array but we asked to sort it along axis=2 (3rd dimension) which broke the code because of out of bound index for dimension.
The way to fix such issues is to first find dimension of array using shape function and then sort it.

In [1]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "msoni00005/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/msoni00005/numpy-array-operations


'https://jovian.ai/msoni00005/numpy-array-operations'

## Function 3 - np.count_nonzero()

This function can be used to count number of nonzero elements in an array.

ARGUMENTS:
np.count_nonzero(arr,axis='value')  : arr is any numpy array and axis is an optional argument , if given it specifies the axis along whcih we need to count nonzero elements.

In [3]:
import numpy as np

In [17]:
# Example 1 - working
arr4 = np.eye(3,3)
arr4

print(f'"no of non zero elements in arr4 are {np.count_nonzero(arr4)}"')

"no of non zero elements in arr4 are 3"


Here it counted number of non zero elements in arr4 and returned its count as result.

In [8]:
# Example 2 - working
arr4

print(f'"no of non zero elements in arr4 along axis 1 are {np.count_nonzero(arr4,axis=1)}"')

"no of non zero elements in arr4 along axis 1 are [1 1 1]"


This snippet code gave list of counts of non zero elements along axis 1 as output. i.e. 1 nonzero in each column.

In [11]:
# Example 3 - breaking (to illustrate when it breaks)
arr4
print(f'"no of non zero elements in arr4 along axis 1 are {np.count_nonzero(arr4,axis=2)}"')

AxisError: axis 2 is out of bounds for array of dimension 2

This is a 2d array ,writing axis as 2 gave an error because it has only 2 dimensions upto index 1.Writing correct dimension will help in fixing this error.

In [12]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "msoni00005/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/msoni00005/numpy-array-operations


'https://jovian.ai/msoni00005/numpy-array-operations'

## Function 4 - np.array_split()

Splitting is a reverse operation of joining / concatenating.We pass an array which we want to split and the number of splits we want.If the array has less elements than required for splitting , it will adjust the end accordingly.

ARGUMENTS:
np.array_split(arr,num,axis='value') :  arr is an array to be splitted and num signifies how many splits we want. and an optional axis parameter.

In [20]:
# Example 1 - working
arr1

np.array_split(arr1,2)

[array([[1., 2.],
        [3., 4.]]),
 array([[5., 6.],
        [7., 8.]])]

In this snippet , the function splitted the array into 2 arrays and returned a list of arrays.Since we didnt mention the axis,by default it splitted along axis 0 .

In [22]:
# Example 2 - working
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

for array in newarr :
    print(array)
    print(" ")

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
 
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
 
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]
 


it splitted the 2D array along axis 1 or along columns into 3 arrays.

In [23]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=2)

print(newarr) 

IndexError: tuple index out of range

The axis argument value given as 2 to np.array_split() function makes the code to break since it raises an indexoutofbounds error.
Writing correct dimension makes the error to go.

In [24]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "msoni00005/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/msoni00005/numpy-array-operations


'https://jovian.ai/msoni00005/numpy-array-operations'

## Function 4 - np.where()

This is a very interesting conditional function which lets us test a condition and do one operation on those that satisfy the condition and another on those that do not satisfy the condition.

ARGUMENTS :
np.where(condition,x,y)  : condition which will be checked which do x for values where condition evaluates to True and y for values where it evaluates to False.

In [40]:
# Example 1 - working
marks = np.array([23,45,65,76,29,87,90,64,97])
result = np.where(marks >= 45,'True','False')

result


array(['False', 'True', 'True', 'True', 'False', 'True', 'True', 'True',
       'True'], dtype='<U5')

Here it created a result array where we stored True at an index at which element was >= 45 in marks array and false otherwise.

In [33]:
# Example 2 - working
arr2

arr2 = np.where(arr2<5 , arr2+10,arr2)
arr2

array([[ 9,  7,  8],
       [ 6,  5, 14],
       [11, 13, 12]])

Here in array2 it incremented the elements by 10 where condition (arr2<5) was true and did nothing for elements where it evaluated to false.

In [39]:
# Example 3 - breaking (to illustrate when it breaks)
marks = np.array([23,45,65,76,29,87,90,64,97])
result = np.where(marks >= 45,'True')

result

ValueError: either both or neither of x and y should be given

We have provided only the x argument along with condition. This is vague and doesn’t tell what to do with values that do not match the condition. 

To fix it we should provide both x and y arguments or neither arguments

In [41]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "msoni00005/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/msoni00005/numpy-array-operations


'https://jovian.ai/msoni00005/numpy-array-operations'

## Conclusion

 In this notebook we saw functions for organizing data, calculations and learnt real life as well as theoretical examples of the same. We also saw the things to avoid when using these functions. There is still a lot more practice needed to get comfortable with this amazing and powerful library.
 This was a good look under the hood of NumPy documentation which is quite vast and almost impossible to know 100%. We found out that there are very useful functions that can do a particular job quickly, efficiently and with less code. That’s the power of NumPy library. 

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Numpy refernce tutorial : https://www.w3schools.com/python/numpy/...

In [42]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "msoni00005/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/msoni00005/numpy-array-operations


'https://jovian.ai/msoni00005/numpy-array-operations'

In [ ]:
jovian.submit(assignment="zero-to-pandas-a2")

<IPython.core.display.Javascript object>